# tasks to complete before running roles
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: add ansible user
      user:
       name: velociraptor
       system: yes

    - name: set up sudo for ansible user
      copy:
       src: files/sudoer_velociraptor
       dest: /etc/sudoers.d/velociraptor
       owner: root
       group: root
       mode: 0440

    - name: add brentc user
      user:
       name: brentc
       system: yes

    - name: set up sudo for brentc 
      copy:
       src: files/sudoer_brentc
       dest: /etc/sudoers.d/brentc
       owner: brentc
       group: brentc
       mode: 0440

    - name: copy .bashrc file
      copy:
       src: files/bashrc
       dest: /home/brentc/.bashrc
       owner: brentc
       group: brentc

    - name: add ansible-pull cron job
      cron:
       name: ansible auto-provision
       user: velociraptor
       minute: "*/10"
       job: ansible-pull -o -U https://github.com/n9bc/personal_ansible_configs.git

  tasks:
  - name: system setup | utilities | install utility packages
    tags: packages,system,settings
    package:
      state: latest
      name:
        - at
        - colordiff
        - curl
        - htop
        - iotop
        - lsof
        - mc
        - mosh
        - ncdu
        - neofetch
        - net-tools
        - nmap
        - ranger
        - rsync
        - screen
        - sshfs
        - tmux
        - traceroute
        - wget
        - whois
        - zsh
  
  - name: system setup | utilities | install man-pages (arch)
    tags: packages,system,settings
    pacman:
      state: latest
      name:
        - man-db
        - man-pages
    when: ansible_distribution == "Archlinux"

